sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t palanugrah/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true palanugrah/docker-react npm run test
